In [2]:
import numpy as np

# Define the angles of rotation
theta_z1 = np.pi / 4  # π/4 radians
theta_y = -np.pi / 3  # -π/3 radians
theta_z2 = np.pi / 2  # π/2 radians

# Create the rotation matrices
R1 = np.array([[np.cos(theta_z1), -np.sin(theta_z1), 0],
               [np.sin(theta_z1), np.cos(theta_z1), 0],
               [0, 0, 1]])

R2 = np.array([[np.cos(theta_y), 0, np.sin(theta_y)],
               [0, 1, 0],
               [-np.sin(theta_y), 0, np.cos(theta_y)]])

R3 = np.array([[np.cos(theta_z2), -np.sin(theta_z2), 0],
               [np.sin(theta_z2), np.cos(theta_z2), 0],
               [0, 0, 1]])

# Multiply the rotation matrices
R = np.dot(R1, np.dot(R2, R3))

# Multiply the transpose of R to R itself to prove R is a rotational matrix as the result is an identity matrix
result_prove_rotational = R.T @ R
determinant = np.linalg.det(R)
R_inverse = np.linalg.inv(R)

print("Below is the rotational matrix R: ")
print("\n", R)
print("\nDeterminant of rotational matrix R:")
print("\n", determinant)
print("\nR is a rotational matrix as result is an identity matrix after multiplying R with R transpose: ")
print("\n", result_prove_rotational)
print("\n R.T is the transpose of R to equate it with R inverse below: ")
print("\n", R.T)
print("\n R_inverse is the inverse of R to equate it with R transpose above: ")
print("\n", R_inverse)

Below is the rotational matrix R: 

 [[-7.07106781e-01 -3.53553391e-01 -6.12372436e-01]
 [ 7.07106781e-01 -3.53553391e-01 -6.12372436e-01]
 [ 5.30287619e-17 -8.66025404e-01  5.00000000e-01]]

Determinant of rotational matrix R:

 1.0

R is a rotational matrix as result is an identity matrix after multiplying R with R transpose: 

 [[1.00000000e+00 1.46601644e-17 1.01628368e-17]
 [1.46601644e-17 1.00000000e+00 1.48741681e-17]
 [1.01628368e-17 1.48741681e-17 1.00000000e+00]]

 R.T is the transpose of R to equate it with R inverse below: 

 [[-7.07106781e-01  7.07106781e-01  5.30287619e-17]
 [-3.53553391e-01 -3.53553391e-01 -8.66025404e-01]
 [-6.12372436e-01 -6.12372436e-01  5.00000000e-01]]

 R_inverse is the inverse of R to equate it with R transpose above: 

 [[-7.07106781e-01  7.07106781e-01 -7.85046229e-17]
 [-3.53553391e-01 -3.53553391e-01 -8.66025404e-01]
 [-6.12372436e-01 -6.12372436e-01  5.00000000e-01]]
